// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: livekit_ipc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from livekit_ipc.proto</summary>
public static partial class LivekitIpcReflection {

  #region Descriptor
  /// <summary>File descriptor for livekit_ipc.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static LivekitIpcReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFsaXZla2l0X2lwYy5wcm90byLhAgoKSVBDTWVzc2FnZRIkCgZidWZmZXIY",
          "ASABKAsyEi5JUENNZXNzYWdlLkJ1ZmZlckgAGqQCCgZCdWZmZXISEwoLdGlt",
          "ZXN0YW1wTnMYASABKAQSDgoGYnVmZmVyGAIgASgMEikKBXZpZGVvGAMgASgL",
          "MhguSVBDTWVzc2FnZS5CdWZmZXIuVmlkZW9IABIvCghhdWRpb0FwcBgEIAEo",
          "CzIbLklQQ01lc3NhZ2UuQnVmZmVyLkF1ZGlvQXBwSAASLwoIYXVkaW9NaWMY",
          "BSABKAsyGy5JUENNZXNzYWdlLkJ1ZmZlci5BdWRpb01pY0gAGkgKBVZpZGVv",
          "Eg4KBmZvcm1hdBgBIAEoDRIQCghyb3RhdGlvbhgCIAEoDRINCgV3aWR0aBgD",
          "IAEoDRIOCgZoZWlnaHQYBCABKA0aCgoIQXVkaW9BcHAaCgoIQXVkaW9NaWNC",
          "BgoEdHlwZUIGCgR0eXBlYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::IPCMessage), global::IPCMessage.Parser, new[]{ "Buffer" }, new[]{ "Type" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::IPCMessage.Types.Buffer), global::IPCMessage.Types.Buffer.Parser, new[]{ "TimestampNs", "Buffer_", "Video", "AudioApp", "AudioMic" }, new[]{ "Type" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::IPCMessage.Types.Buffer.Types.Video), global::IPCMessage.Types.Buffer.Types.Video.Parser, new[]{ "Format", "Rotation", "Width", "Height" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::IPCMessage.Types.Buffer.Types.AudioApp), global::IPCMessage.Types.Buffer.Types.AudioApp.Parser, null, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::IPCMessage.Types.Buffer.Types.AudioMic), global::IPCMessage.Types.Buffer.Types.AudioMic.Parser, null, null, null, null, null)})})
        }));
  }
  #endregion

}
#region Messages
public sealed partial class IPCMessage : pb::IMessage<IPCMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<IPCMessage> _parser = new pb::MessageParser<IPCMessage>(() => new IPCMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<IPCMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LivekitIpcReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IPCMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IPCMessage(IPCMessage other) : this() {
    switch (other.TypeCase) {
      case TypeOneofCase.Buffer:
        Buffer = other.Buffer.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IPCMessage Clone() {
    return new IPCMessage(this);
  }

  /// <summary>Field number for the "buffer" field.</summary>
  public const int BufferFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::IPCMessage.Types.Buffer Buffer {
    get { return typeCase_ == TypeOneofCase.Buffer ? (global::IPCMessage.Types.Buffer) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Buffer;
    }
  }

  private object type_;
  /// <summary>Enum of possible cases for the "type" oneof.</summary>
  public enum TypeOneofCase {
    None = 0,
    Buffer = 1,
  }
  private TypeOneofCase typeCase_ = TypeOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public TypeOneofCase TypeCase {
    get { return typeCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearType() {
    typeCase_ = TypeOneofCase.None;
    type_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as IPCMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(IPCMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Buffer, other.Buffer)) return false;
    if (TypeCase != other.TypeCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (typeCase_ == TypeOneofCase.Buffer) hash ^= Buffer.GetHashCode();
    hash ^= (int) typeCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (typeCase_ == TypeOneofCase.Buffer) {
      output.WriteRawTag(10);
      output.WriteMessage(Buffer);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (typeCase_ == TypeOneofCase.Buffer) {
      output.WriteRawTag(10);
      output.WriteMessage(Buffer);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (typeCase_ == TypeOneofCase.Buffer) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Buffer);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(IPCMessage other) {
    if (other == null) {
      return;
    }
    switch (other.TypeCase) {
      case TypeOneofCase.Buffer:
        if (Buffer == null) {
          Buffer = new global::IPCMessage.Types.Buffer();
        }
        Buffer.MergeFrom(other.Buffer);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::IPCMessage.Types.Buffer subBuilder = new global::IPCMessage.Types.Buffer();
          if (typeCase_ == TypeOneofCase.Buffer) {
            subBuilder.MergeFrom(Buffer);
          }
          input.ReadMessage(subBuilder);
          Buffer = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::IPCMessage.Types.Buffer subBuilder = new global::IPCMessage.Types.Buffer();
          if (typeCase_ == TypeOneofCase.Buffer) {
            subBuilder.MergeFrom(Buffer);
          }
          input.ReadMessage(subBuilder);
          Buffer = subBuilder;
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the IPCMessage message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public sealed partial class Buffer : pb::IMessage<Buffer>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<Buffer> _parser = new pb::MessageParser<Buffer>(() => new Buffer());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pb::MessageParser<Buffer> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::IPCMessage.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Buffer() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Buffer(Buffer other) : this() {
        timestampNs_ = other.timestampNs_;
        buffer_ = other.buffer_;
        switch (other.TypeCase) {
          case TypeOneofCase.Video:
            Video = other.Video.Clone();
            break;
          case TypeOneofCase.AudioApp:
            AudioApp = other.AudioApp.Clone();
            break;
          case TypeOneofCase.AudioMic:
            AudioMic = other.AudioMic.Clone();
            break;
        }

        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Buffer Clone() {
        return new Buffer(this);
      }

      /// <summary>Field number for the "timestampNs" field.</summary>
      public const int TimestampNsFieldNumber = 1;
      private ulong timestampNs_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public ulong TimestampNs {
        get { return timestampNs_; }
        set {
          timestampNs_ = value;
        }
      }

      /// <summary>Field number for the "buffer" field.</summary>
      public const int Buffer_FieldNumber = 2;
      private pb::ByteString buffer_ = pb::ByteString.Empty;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public pb::ByteString Buffer_ {
        get { return buffer_; }
        set {
          buffer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      /// <summary>Field number for the "video" field.</summary>
      public const int VideoFieldNumber = 3;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public global::IPCMessage.Types.Buffer.Types.Video Video {
        get { return typeCase_ == TypeOneofCase.Video ? (global::IPCMessage.Types.Buffer.Types.Video) type_ : null; }
        set {
          type_ = value;
          typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Video;
        }
      }

      /// <summary>Field number for the "audioApp" field.</summary>
      public const int AudioAppFieldNumber = 4;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public global::IPCMessage.Types.Buffer.Types.AudioApp AudioApp {
        get { return typeCase_ == TypeOneofCase.AudioApp ? (global::IPCMessage.Types.Buffer.Types.AudioApp) type_ : null; }
        set {
          type_ = value;
          typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.AudioApp;
        }
      }

      /// <summary>Field number for the "audioMic" field.</summary>
      public const int AudioMicFieldNumber = 5;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public global::IPCMessage.Types.Buffer.Types.AudioMic AudioMic {
        get { return typeCase_ == TypeOneofCase.AudioMic ? (global::IPCMessage.Types.Buffer.Types.AudioMic) type_ : null; }
        set {
          type_ = value;
          typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.AudioMic;
        }
      }

      private object type_;
      /// <summary>Enum of possible cases for the "type" oneof.</summary>
      public enum TypeOneofCase {
        None = 0,
        Video = 3,
        AudioApp = 4,
        AudioMic = 5,
      }
      private TypeOneofCase typeCase_ = TypeOneofCase.None;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public TypeOneofCase TypeCase {
        get { return typeCase_; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void ClearType() {
        typeCase_ = TypeOneofCase.None;
        type_ = null;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override bool Equals(object other) {
        return Equals(other as Buffer);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public bool Equals(Buffer other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (TimestampNs != other.TimestampNs) return false;
        if (Buffer_ != other.Buffer_) return false;
        if (!object.Equals(Video, other.Video)) return false;
        if (!object.Equals(AudioApp, other.AudioApp)) return false;
        if (!object.Equals(AudioMic, other.AudioMic)) return false;
        if (TypeCase != other.TypeCase) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override int GetHashCode() {
        int hash = 1;
        if (TimestampNs != 0UL) hash ^= TimestampNs.GetHashCode();
        if (Buffer_.Length != 0) hash ^= Buffer_.GetHashCode();
        if (typeCase_ == TypeOneofCase.Video) hash ^= Video.GetHashCode();
        if (typeCase_ == TypeOneofCase.AudioApp) hash ^= AudioApp.GetHashCode();
        if (typeCase_ == TypeOneofCase.AudioMic) hash ^= AudioMic.GetHashCode();
        hash ^= (int) typeCase_;
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (TimestampNs != 0UL) {
          output.WriteRawTag(8);
          output.WriteUInt64(TimestampNs);
        }
        if (Buffer_.Length != 0) {
          output.WriteRawTag(18);
          output.WriteBytes(Buffer_);
        }
        if (typeCase_ == TypeOneofCase.Video) {
          output.WriteRawTag(26);
          output.WriteMessage(Video);
        }
        if (typeCase_ == TypeOneofCase.AudioApp) {
          output.WriteRawTag(34);
          output.WriteMessage(AudioApp);
        }
        if (typeCase_ == TypeOneofCase.AudioMic) {
          output.WriteRawTag(42);
          output.WriteMessage(AudioMic);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (TimestampNs != 0UL) {
          output.WriteRawTag(8);
          output.WriteUInt64(TimestampNs);
        }
        if (Buffer_.Length != 0) {
          output.WriteRawTag(18);
          output.WriteBytes(Buffer_);
        }
        if (typeCase_ == TypeOneofCase.Video) {
          output.WriteRawTag(26);
          output.WriteMessage(Video);
        }
        if (typeCase_ == TypeOneofCase.AudioApp) {
          output.WriteRawTag(34);
          output.WriteMessage(AudioApp);
        }
        if (typeCase_ == TypeOneofCase.AudioMic) {
          output.WriteRawTag(42);
          output.WriteMessage(AudioMic);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public int CalculateSize() {
        int size = 0;
        if (TimestampNs != 0UL) {
          size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimestampNs);
        }
        if (Buffer_.Length != 0) {
          size += 1 + pb::CodedOutputStream.ComputeBytesSize(Buffer_);
        }
        if (typeCase_ == TypeOneofCase.Video) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(Video);
        }
        if (typeCase_ == TypeOneofCase.AudioApp) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(AudioApp);
        }
        if (typeCase_ == TypeOneofCase.AudioMic) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(AudioMic);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(Buffer other) {
        if (other == null) {
          return;
        }
        if (other.TimestampNs != 0UL) {
          TimestampNs = other.TimestampNs;
        }
        if (other.Buffer_.Length != 0) {
          Buffer_ = other.Buffer_;
        }
        switch (other.TypeCase) {
          case TypeOneofCase.Video:
            if (Video == null) {
              Video = new global::IPCMessage.Types.Buffer.Types.Video();
            }
            Video.MergeFrom(other.Video);
            break;
          case TypeOneofCase.AudioApp:
            if (AudioApp == null) {
              AudioApp = new global::IPCMessage.Types.Buffer.Types.AudioApp();
            }
            AudioApp.MergeFrom(other.AudioApp);
            break;
          case TypeOneofCase.AudioMic:
            if (AudioMic == null) {
              AudioMic = new global::IPCMessage.Types.Buffer.Types.AudioMic();
            }
            AudioMic.MergeFrom(other.AudioMic);
            break;
        }

        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 8: {
              TimestampNs = input.ReadUInt64();
              break;
            }
            case 18: {
              Buffer_ = input.ReadBytes();
              break;
            }
            case 26: {
              global::IPCMessage.Types.Buffer.Types.Video subBuilder = new global::IPCMessage.Types.Buffer.Types.Video();
              if (typeCase_ == TypeOneofCase.Video) {
                subBuilder.MergeFrom(Video);
              }
              input.ReadMessage(subBuilder);
              Video = subBuilder;
              break;
            }
            case 34: {
              global::IPCMessage.Types.Buffer.Types.AudioApp subBuilder = new global::IPCMessage.Types.Buffer.Types.AudioApp();
              if (typeCase_ == TypeOneofCase.AudioApp) {
                subBuilder.MergeFrom(AudioApp);
              }
              input.ReadMessage(subBuilder);
              AudioApp = subBuilder;
              break;
            }
            case 42: {
              global::IPCMessage.Types.Buffer.Types.AudioMic subBuilder = new global::IPCMessage.Types.Buffer.Types.AudioMic();
              if (typeCase_ == TypeOneofCase.AudioMic) {
                subBuilder.MergeFrom(AudioMic);
              }
              input.ReadMessage(subBuilder);
              AudioMic = subBuilder;
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 8: {
              TimestampNs = input.ReadUInt64();
              break;
            }
            case 18: {
              Buffer_ = input.ReadBytes();
              break;
            }
            case 26: {
              global::IPCMessage.Types.Buffer.Types.Video subBuilder = new global::IPCMessage.Types.Buffer.Types.Video();
              if (typeCase_ == TypeOneofCase.Video) {
                subBuilder.MergeFrom(Video);
              }
              input.ReadMessage(subBuilder);
              Video = subBuilder;
              break;
            }
            case 34: {
              global::IPCMessage.Types.Buffer.Types.AudioApp subBuilder = new global::IPCMessage.Types.Buffer.Types.AudioApp();
              if (typeCase_ == TypeOneofCase.AudioApp) {
                subBuilder.MergeFrom(AudioApp);
              }
              input.ReadMessage(subBuilder);
              AudioApp = subBuilder;
              break;
            }
            case 42: {
              global::IPCMessage.Types.Buffer.Types.AudioMic subBuilder = new global::IPCMessage.Types.Buffer.Types.AudioMic();
              if (typeCase_ == TypeOneofCase.AudioMic) {
                subBuilder.MergeFrom(AudioMic);
              }
              input.ReadMessage(subBuilder);
              AudioMic = subBuilder;
              break;
            }
          }
        }
      }
      #endif

      #region Nested types
      /// <summary>Container for nested types declared in the Buffer message type.</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static partial class Types {
        public sealed partial class Video : pb::IMessage<Video>
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            , pb::IBufferMessage
        #endif
        {
          private static readonly pb::MessageParser<Video> _parser = new pb::MessageParser<Video>(() => new Video());
          private pb::UnknownFieldSet _unknownFields;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public static pb::MessageParser<Video> Parser { get { return _parser; } }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public static pbr::MessageDescriptor Descriptor {
            get { return global::IPCMessage.Types.Buffer.Descriptor.NestedTypes[0]; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          pbr::MessageDescriptor pb::IMessage.Descriptor {
            get { return Descriptor; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public Video() {
            OnConstruction();
          }

          partial void OnConstruction();

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public Video(Video other) : this() {
            format_ = other.format_;
            rotation_ = other.rotation_;
            width_ = other.width_;
            height_ = other.height_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public Video Clone() {
            return new Video(this);
          }

          /// <summary>Field number for the "format" field.</summary>
          public const int FormatFieldNumber = 1;
          private uint format_;
          /// <summary>
          /// CVPixelBuffer's FormatType
          /// </summary>
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public uint Format {
            get { return format_; }
            set {
              format_ = value;
            }
          }

          /// <summary>Field number for the "rotation" field.</summary>
          public const int RotationFieldNumber = 2;
          private uint rotation_;
          /// <summary>
          /// RTCVideoRotation
          /// </summary>
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public uint Rotation {
            get { return rotation_; }
            set {
              rotation_ = value;
            }
          }

          /// <summary>Field number for the "width" field.</summary>
          public const int WidthFieldNumber = 3;
          private uint width_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public uint Width {
            get { return width_; }
            set {
              width_ = value;
            }
          }

          /// <summary>Field number for the "height" field.</summary>
          public const int HeightFieldNumber = 4;
          private uint height_;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public uint Height {
            get { return height_; }
            set {
              height_ = value;
            }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public override bool Equals(object other) {
            return Equals(other as Video);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public bool Equals(Video other) {
            if (ReferenceEquals(other, null)) {
              return false;
            }
            if (ReferenceEquals(other, this)) {
              return true;
            }
            if (Format != other.Format) return false;
            if (Rotation != other.Rotation) return false;
            if (Width != other.Width) return false;
            if (Height != other.Height) return false;
            return Equals(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public override int GetHashCode() {
            int hash = 1;
            if (Format != 0) hash ^= Format.GetHashCode();
            if (Rotation != 0) hash ^= Rotation.GetHashCode();
            if (Width != 0) hash ^= Width.GetHashCode();
            if (Height != 0) hash ^= Height.GetHashCode();
            if (_unknownFields != null) {
              hash ^= _unknownFields.GetHashCode();
            }
            return hash;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public override string ToString() {
            return pb::JsonFormatter.ToDiagnosticString(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public void WriteTo(pb::CodedOutputStream output) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
          #else
            if (Format != 0) {
              output.WriteRawTag(8);
              output.WriteUInt32(Format);
            }
            if (Rotation != 0) {
              output.WriteRawTag(16);
              output.WriteUInt32(Rotation);
            }
            if (Width != 0) {
              output.WriteRawTag(24);
              output.WriteUInt32(Width);
            }
            if (Height != 0) {
              output.WriteRawTag(32);
              output.WriteUInt32(Height);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(output);
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
            if (Format != 0) {
              output.WriteRawTag(8);
              output.WriteUInt32(Format);
            }
            if (Rotation != 0) {
              output.WriteRawTag(16);
              output.WriteUInt32(Rotation);
            }
            if (Width != 0) {
              output.WriteRawTag(24);
              output.WriteUInt32(Width);
            }
            if (Height != 0) {
              output.WriteRawTag(32);
              output.WriteUInt32(Height);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(ref output);
            }
          }
          #endif

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public int CalculateSize() {
            int size = 0;
            if (Format != 0) {
              size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Format);
            }
            if (Rotation != 0) {
              size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Rotation);
            }
            if (Width != 0) {
              size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Width);
            }
            if (Height != 0) {
              size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Height);
            }
            if (_unknownFields != null) {
              size += _unknownFields.CalculateSize();
            }
            return size;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public void MergeFrom(Video other) {
            if (other == null) {
              return;
            }
            if (other.Format != 0) {
              Format = other.Format;
            }
            if (other.Rotation != 0) {
              Rotation = other.Rotation;
            }
            if (other.Width != 0) {
              Width = other.Width;
            }
            if (other.Height != 0) {
              Height = other.Height;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public void MergeFrom(pb::CodedInputStream input) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
          #else
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
              switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                  break;
                case 8: {
                  Format = input.ReadUInt32();
                  break;
                }
                case 16: {
                  Rotation = input.ReadUInt32();
                  break;
                }
                case 24: {
                  Width = input.ReadUInt32();
                  break;
                }
                case 32: {
                  Height = input.ReadUInt32();
                  break;
                }
              }
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
              switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                  break;
                case 8: {
                  Format = input.ReadUInt32();
                  break;
                }
                case 16: {
                  Rotation = input.ReadUInt32();
                  break;
                }
                case 24: {
                  Width = input.ReadUInt32();
                  break;
                }
                case 32: {
                  Height = input.ReadUInt32();
                  break;
                }
              }
            }
          }
          #endif

        }

        public sealed partial class AudioApp : pb::IMessage<AudioApp>
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            , pb::IBufferMessage
        #endif
        {
          private static readonly pb::MessageParser<AudioApp> _parser = new pb::MessageParser<AudioApp>(() => new AudioApp());
          private pb::UnknownFieldSet _unknownFields;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public static pb::MessageParser<AudioApp> Parser { get { return _parser; } }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public static pbr::MessageDescriptor Descriptor {
            get { return global::IPCMessage.Types.Buffer.Descriptor.NestedTypes[1]; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          pbr::MessageDescriptor pb::IMessage.Descriptor {
            get { return Descriptor; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public AudioApp() {
            OnConstruction();
          }

          partial void OnConstruction();

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public AudioApp(AudioApp other) : this() {
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public AudioApp Clone() {
            return new AudioApp(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public override bool Equals(object other) {
            return Equals(other as AudioApp);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public bool Equals(AudioApp other) {
            if (ReferenceEquals(other, null)) {
              return false;
            }
            if (ReferenceEquals(other, this)) {
              return true;
            }
            return Equals(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public override int GetHashCode() {
            int hash = 1;
            if (_unknownFields != null) {
              hash ^= _unknownFields.GetHashCode();
            }
            return hash;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public override string ToString() {
            return pb::JsonFormatter.ToDiagnosticString(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public void WriteTo(pb::CodedOutputStream output) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
          #else
            if (_unknownFields != null) {
              _unknownFields.WriteTo(output);
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
            if (_unknownFields != null) {
              _unknownFields.WriteTo(ref output);
            }
          }
          #endif

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public int CalculateSize() {
            int size = 0;
            if (_unknownFields != null) {
              size += _unknownFields.CalculateSize();
            }
            return size;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public void MergeFrom(AudioApp other) {
            if (other == null) {
              return;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public void MergeFrom(pb::CodedInputStream input) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
          #else
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
              switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                  break;
              }
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
              switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                  break;
              }
            }
          }
          #endif

        }

        public sealed partial class AudioMic : pb::IMessage<AudioMic>
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            , pb::IBufferMessage
        #endif
        {
          private static readonly pb::MessageParser<AudioMic> _parser = new pb::MessageParser<AudioMic>(() => new AudioMic());
          private pb::UnknownFieldSet _unknownFields;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public static pb::MessageParser<AudioMic> Parser { get { return _parser; } }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public static pbr::MessageDescriptor Descriptor {
            get { return global::IPCMessage.Types.Buffer.Descriptor.NestedTypes[2]; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          pbr::MessageDescriptor pb::IMessage.Descriptor {
            get { return Descriptor; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public AudioMic() {
            OnConstruction();
          }

          partial void OnConstruction();

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public AudioMic(AudioMic other) : this() {
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public AudioMic Clone() {
            return new AudioMic(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public override bool Equals(object other) {
            return Equals(other as AudioMic);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public bool Equals(AudioMic other) {
            if (ReferenceEquals(other, null)) {
              return false;
            }
            if (ReferenceEquals(other, this)) {
              return true;
            }
            return Equals(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public override int GetHashCode() {
            int hash = 1;
            if (_unknownFields != null) {
              hash ^= _unknownFields.GetHashCode();
            }
            return hash;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public override string ToString() {
            return pb::JsonFormatter.ToDiagnosticString(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public void WriteTo(pb::CodedOutputStream output) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
          #else
            if (_unknownFields != null) {
              _unknownFields.WriteTo(output);
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
            if (_unknownFields != null) {
              _unknownFields.WriteTo(ref output);
            }
          }
          #endif

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public int CalculateSize() {
            int size = 0;
            if (_unknownFields != null) {
              size += _unknownFields.CalculateSize();
            }
            return size;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public void MergeFrom(AudioMic other) {
            if (other == null) {
              return;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          public void MergeFrom(pb::CodedInputStream input) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
          #else
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
              switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                  break;
              }
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
              switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                  break;
              }
            }
          }
          #endif

        }

      }
      #endregion

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
